### PR TITLE
update to 0.22.1

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@synapticarbors : It fails because "setuptools downloading is disabled in conda-build". Could you please suggest something.

**Comment by synapticarbors** [comment]
It looks like `isort` was added in the `setup.py`:

https://github.com/alex/django-taggit/blob/master/setup.py#L43-L45

so this needs to be added as a `build` requirement. Also, I don't think you need to add `setuptools` as a `run` requirement. 

Could you also re-render the feedstock while you're at it?

https://conda-forge.org/docs/conda_smithy.html

**Comment by sannykr** [comment]
@kwilcox: Could you please review and merge.
I have not re-rendered the feedstock yet, I will do that now.

**Comment by kwilcox** [comment]
Commit a rerender and ill merge, thanks!

**Comment by sannykr** [comment]
@synapticarbors : Thanks. I will keep that in mind in future. I used [skip ci][ci skip] in the commit message after rerendering the feedstock, and I think it should be okay. It had already passed all checks.

**Comment by kwilcox** [comment]
I'm not comfortable merging this as it stands. Can you please rebase all of these commits onto master into (2) commits:

1. The re-render
2. The version bump

**Comment by sannykr** [comment]
@kwilcox : Do you want me to create   a different branch, make two commits (rerender and version bump), and then make a pull request from that branch, and close this branch?

**Comment by kwilcox** [comment]
That would be great, thanks.

**Comment by sannykr** [comment]
@kwilcox : I created a new branch and have made two commits. Can you please look at that and let me know if everything is alright while it is running.

**Pull request closed without merging**
